global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
//global using Microsoft.AspNetCore.Mvc;
//global using System.Xml.Serialization;
//global using System.Reflection;
global using System.ComponentModel.DataAnnotations;
//global using System.IdentityModel.Tokens.Jwt;
//global using System.Security.Claims;
//global using System.Text;
//global using Microsoft.IdentityModel.Tokens;
//global using Microsoft.AspNetCore.Authentication.JwtBearer;
//global using Microsoft.AspNetCore.Authorization
